### PR TITLE
Pluto demo

### PR DESCRIPTION
**Pull request by jjgomezcadenas**
This PR adds the first tutorial Pluto notebook.

### CODE REVIEW

**Comment by andLaing** [comment]
Is there anything else to be added to this PR or can it be merged?

**Comment by jjgomezcadenas** [comment]
I will be adding a few more notebooks the next few days.

**Comment by andLaing** [comment]
OK, so I'll add pluto into the master in a separate PR. It not being there is inhibiting work.

**Comment by jjgomezcadenas** [comment]
Rather than this, merge, and I will open a new PR

**Pull request merged**
